name: Retrain Model CI

# Workflow ini akan berjalan setiap kali ada push ke branch 'main'
on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest # Menggunakan runner terbaru dari GitHub

    steps:
    # Langkah 1: Checkout kode dari repositori
    - name: Checkout repository
      uses: actions/checkout@v4

    # Langkah 2: Setup environment Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Langkah 3: Install dependensi yang dibutuhkan untuk menjalankan MLflow
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow

    # Langkah 4: Jalankan MLflow Project
    # Perintah ini akan otomatis membaca MLproject, membuat environment conda, dan menjalankan command
    - name: Run MLflow project
      run: mlflow run MLProject

    # Langkah 5: Simpan artefak MLflow (folder mlruns)
    # Ini adalah kunci untuk poin "Skilled"
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts # Nama artefak yang akan diunggah
        path: MLProject/mlruns # Path ke folder output MLflow